apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pdcm-web-ui
  namespace: pdcm-web-ui
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: pdcm-web-ui
    spec:
      containers:
        - name: pdcm-web-ui
          image: "pdxfinder/pdcm-web-ui:prod"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
